Replaced .name with .display for power badge
shadytradesman/The-Contract-Website pull request #107
Opened 2021-03-13 05:41 UTC by Hawful

Here's an example of what the display looks like. I think the parens are... _okay_ let me know what you think, maybe we could add a new .display_snippet to the model or something.
![EnhancementDrawbackDisplay](https://user-images.githubusercontent.com/7707883/111020563-b4a72100-837b-11eb-8ada-46f1acaa04c4.png)

2021-03-14 03:14 UTC, shadytradesman requested changes
Good start, but I have a feeling this won't look very good on Powers with many enhancements and drawbacks. The list should probably be one per line instead of wrapping and outlined-pills. We should also display the details text field if there is one and what the user entered. Finally, I think we should fill the mouseover text with the enhancement's eratta instead of its description (which will now always be displayed).

2021-03-14 03:28 UTC, Hawful commented
Great, I'll take a look at that now

2021-03-14 05:54 UTC, shadytradesman commented
To save space you might consider taking out the "System:" header.

2021-03-14 19:44 UTC, Hawful commented
Ticked all the boxes of requests, here's a screenshot of the new look
![NewPowerBadge](https://user-images.githubusercontent.com/7707883/111081961-09a17f00-84c3-11eb-8d97-8bb5ab7a2027.png)

2021-03-15 00:09 UTC, shadytradesman approved these changes
Looks great! Thanks for paying attention to the conditionals

2021-03-15 00:09 UTC, merged